"""
Django settings for ShiRunProject project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!!9a308c=d%o_vvx5d#aspuu+n3d6(q=!@2*-pdf_pj*p+1=4w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'salary.apps.SalaryConfig',
    'rbac',
    'salary.templatetags',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 加入效验是否登陆过的中间件
    # 'salary.utils.middlewares.LoginMiddleWare',
]

ROOT_URLCONF = 'ShiRunProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates/customer'),
                 os.path.join(BASE_DIR, 'templates/car'),
                 os.path.join(BASE_DIR, 'templates/oil'),
                 os.path.join(BASE_DIR, 'templates/oilwarehouse'),
                 os.path.join(BASE_DIR, 'templates/petrolstation'),
                 os.path.join(BASE_DIR, 'templates/petrolstation2oilwarehouse'),
                 os.path.join(BASE_DIR, 'templates/customer2mileage'),
                 os.path.join(BASE_DIR, 'templates/information'),
                 os.path.join(BASE_DIR, 'templates/settlement'),
                 os.path.join(BASE_DIR, 'templates/userinfo'),
                 os.path.join(BASE_DIR, 'templates/earning'),
                 os.path.join(BASE_DIR, 'templates/cartype'),
                 os.path.join(BASE_DIR, 'templates/petrolstation12'),
                 os.path.join(BASE_DIR, 'templates/petrolstation30'),
                 os.path.join(BASE_DIR, 'templates/month_salary'),
                 os.path.join(BASE_DIR, 'templates/month_work_days'),
                 ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShiRunProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# 设置数据库
DATABASES = {
    'default': {
        # 引擎
        'ENGINE': 'django.db.backends.mysql',
        # 数据库名称
        'NAME': 'shirun',
        # 数据库密码
        'PASSWORD': '995995',
        # 数据库用户
        'USER': 'root',
        # 主机名
        'HOST': '127.0.0.1',
        # 端口
        'PORT': '3306',
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'

# 修改语言为汉字
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# 时间相差8个小时
USE_TZ = False

STATIC_URL = '/static/'

# 设置静态文件的查找路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# 自定义配置登录验证返回路径
LOGIN_URL = '/login/'

# media配置,用户上传的文件都默认放在这个文件夹中
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# 如果使用继承的方式使用内置的auth模块,需要设置此配置,默认用户认证时使用的是哪张表
AUTH_USER_MODEL = 'salary.UserInfo'
