# Generated by Django 2.1.1 on 2020-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinformation',
            name='earning',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='工资结算'),
        ),
        migrations.AlterField(
            model_name='staticinformation',
            name='long_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='长途运费'),
        ),
        migrations.AlterField(
            model_name='staticinformation',
            name='short_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='短途运费'),
        ),
    ]
