# Generated by Django 2.1.1 on 2020-03-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20200303_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinformation',
            name='oiltank_number',
            field=models.IntegerField(default=0, verbose_name='油罐数'),
        ),
    ]
