# Generated by Django 2.1.1 on 2020-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20200303_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='oiltank_number',
            field=models.IntegerField(default=0, verbose_name='灌桶数'),
        ),
    ]
