# Generated by Django 2.1.1 on 2020-03-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20200303_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='deliver_time',
            field=models.DateField(verbose_name='配送时间'),
        ),
    ]
